### ISSUE TITLE
Unable to resolve action `GongT/actions-recreate-release@v1`

### ISSUE THREAD

**Issue by krobelus** [GongT/actions-recreate-release#1]
See https://github.com/krobelus/kak-lsp/runs/1367544507

I simply used

```
    - name: Create Release
      uses: GongT/actions-recreate-release@v1
```

like described in the readme. Is there anything else needed to do so GH Actions can find it?

**Comment by krobelus** [comment]
For the record, as a workaround I'm simply deleting my old release with 

```
curl -H "Authorization: token $GITHUB_TOKEN" -XDELETE "$GITHUB_API_URL/repos/$user/$repo/releases/$id"
```

**Comment by GongT** [comment]
🤦‍♂️ I forgot to publish it. LOL
